
Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (tc21_pthonce.c:86)

Thread #x was created
   ...
   by 0x........: pthread_create@* (hg_intercepts.c:...)
   by 0x........: main (tc21_pthonce.c:86)

Possible data race during read of size 4 at 0x........ by thread #x
   at 0x........: child (tc21_pthonce.c:74)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...
 This conflicts with a previous write of size 4 by thread #x
   at 0x........: child (tc21_pthonce.c:74)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...
 Location 0x........ is 0 bytes inside local var "unprotected2"
 declared at tc21_pthonce.c:51, in frame #x of thread x

Possible data race during write of size 4 at 0x........ by thread #x
   at 0x........: child (tc21_pthonce.c:74)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...
 This conflicts with a previous write of size 4 by thread #x
   at 0x........: child (tc21_pthonce.c:74)
   by 0x........: mythread_wrapper (hg_intercepts.c:...)
   ...
 Location 0x........ is 0 bytes inside local var "unprotected2"
 declared at tc21_pthonce.c:51, in frame #x of thread x


ERROR SUMMARY: 2 errors from 2 contexts (suppressed: 0 from 0)
